### ISSUE TITLE
Trying to get this to work on my tumblr...

### ISSUE THREAD

**Issue by jam35r2** [macleodsawyer/NoPo#2]
But it's not working... I have two `{block:posts}` on my custom theme... the first one is HUGE... this is how it starts:

```
{block:Posts}

{block:IndexPage}

{block:Answer}
<div class="post type_text" id="post-{PostID}"><div class="post_margin_adjustment"><div class="post_relati
```

The second `{block:posts}` looks like the one that should be edited... it looks like this:

```
{block:Posts}
<div id="post_notes"><ol class="notes"><li class="notes_scroll_down">▼</li></ol><ol class="notes">{block:Caption}<li class="notes_headline"><span class="notes_headline_inner">{Caption}</span></li>{/block:Caption}{block:Artist}<li class="note">{block:TrackName}"{TrackName}"&nbsp;-&nbsp;{/block:TrackName}{block:Album}{Album} - {/block:Album}{Artist}</li>{/block:Artist}</ol><ol class="notes"><li class="notes_tag">{block:NoteCount}<span class="notes_tag_button">{NoteCountWithLabel}</span>{/block:NoteCount}{block:Date}<span class="notes_date_span">Timestamp: {DayOfWeek} {Year}/{MonthNumberWithZero}/{DayOfMonthWithZero} {24Hour}:{Minutes}:{Seconds}</span>{/block:Date}{block:RebloggedFrom}<span class="action"><a class="notes_tag_button type_source" href="{ReblogParentURL}">Via: {ReblogParentName}</a></span>{/block:RebloggedFrom}{block:ContentSource}<span class="action"><a class="notes_tag_button type_source" href="{SourceURL}" title="{SourceTitle}">Source: {SourceTitle}</a></span>{/block:ContentSource}{block:HasTags}{block:Tags}<span class="action notes_tag_title_case"><a class="notes_tag_button" href="{TagURL}">{Tag}</a></span>{/block:Tags}{/block:HasTags}</li></ol>{block:PostNotes}{PostNotes}{/block:PostNotes}<ol class="notes">
<!-- To personalise the tweet share button add after the class attribute: data-via="YOUR_USER_NAME_WITHOUT_THE_@" data-hashtags="A_HASHTAG_WITHOUT_THE_#" --><li class="note perma_tweet">
{block:IfTweetThis}<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>{/block:IfTweetThis}</li></ol><ol class="notes"><li class="notes_scroll_to_top">▲</li></ol></div>
{/block:Posts}
```

Any ideas? 
I do have a custom css area so that's good.

Thanks for offering to help.

**Comment by macleod-ee** [comment]
You appear to have a **very** overly complicated made tumblr theme. 

Follow the steps, but insert the codes from the instructions inside every

``` html
<div class="post ... "> and <div i="post_notes">
```

Thanks for messaging me on tumblr!

**Comment by jam35r2** [comment]
Hey thanks for replying, but I think the comment section cut off your code?

But yeah, the coding seems kinda like a mess... I would change themes, but I can't find another one that I like (and I've been keeping my eye out for like a year lol).

**Comment by macleod-ee** [comment]
@jam35r2 updated my comment, forgot GitHub hides the code snippets unless properly syntax'd.

**Comment by jam35r2** [comment]
It works! It took like 40 minutes to put it in all the `{TagAsClasses}` in the `<div class="post ...">` but it was worth it in the end lol. 

I didn't know what `<div i="...">` meant so I just put the `{TagAsClasses}` after all the `<div id="...">` as well... hopefully it doesn't screw up the theme... it looks fine. 

I also put the `{TagAsClasses}` after the `class` in `<div title="....." class="...">`

Thank you so much :)

**Comment by mxnon** [comment]
it's not working for me either... I have two {block:posts} on my custom theme as well..
first one is like this:
	{block:IndexPage}	  
    <div class="posts" id="allposts">
  {/block:IndexPage}
  {block:Posts}
    {block:PermalinkPage}    
    <div class="postbox" >
    <div class="postcontent rounded-corners box-shadow">
    {/block:PermalinkPage}
    {block:IndexPage}
    <div class="box rounded-corners box-shadow">    
    {/block:IndexPage}

and the second:

   {block:PermalinkPage}
    <div style="clear: both;"></div>
    </div>
    {/block:PermalinkPage}
              
    {/block:Posts}
	{block:IndexPage}
