### ISSUE TITLE
Two+ columns and <article> tags for posts!

### ISSUE THREAD

**Issue by fferreira101** [macleodsawyer/NoPo#3]
Code worked great for single column option on my theme! But I want to use the 2+ column look.
In your fix you use the code:

{block:IndexPage}

<div class="(insert whatever you found in step 7)">
<small><a href=""></a></h2></small>
</div>

{/block:IndexPage}

But how do I apply this to my theme since it has the <article> class instead of <div> ?
thank you!

**Comment by macleod-ee** [comment]
Hi I would love to help you but I think github got rid of tthe HTML examples!
