### ISSUE TITLE
2+column theme problems

### ISSUE THREAD

**Issue by Isdelth** [macleodsawyer/NoPo#4]
Hello Sawyer! I followed the steps for your code, and so far I got my theme to the point where it all turns into 1 column (my current theme is a 2+ column one), however when I try to follow the instructions to fix this, I haven't been able to fix it.

 what exactly do you mean when you say "(insert whatever you found in step 7)"?
 step 7 are the instructions to fix the two column issue @_@ 

I've tried adding different things like "post", "text post", "{Post ID}" with no succes :/ , your help would be greatly appreciated! Thanks in advance! :)

**Comment by macleod-ee** [comment]
Did you end up figuring it out?

**Comment by Isdelth** [comment]
Yessir, It sorted itself out somehow haha

**Comment by macleod-ee** [comment]
Awesome! My code could be of help!
